spring:
  config:
    import:
      - security.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SERVER_DB_URL}
    username: ${SERVER_DB_USERNAME}
    password: ${SERVER_DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  sql.init.mode: always
logging:
  level:
    org:
      springframework:
        web: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
